# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Docsy Public Docs
site_url: https://docs.getdocsy.com
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
repo_url: https://github.com/getdocsy/docs
edit_uri: "edit/main/docs/"
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: getdocsy/docs
      branch: main
